### ISSUE TITLE
warnings

### ISSUE THREAD

**Issue by Qavai** [bentasker/PHP-GPX-Ingest#10] opened 2016-02-21 07:57 UTC
Warning: max() [function.max]: Array must contain at least one element in \GPXIngest.php on line 947

Warning: max() [function.max]: Array must contain at least one element in \GPXIngest.php on line 948

Warning: min() [function.min]: Array must contain at least one element in \GPXIngest.php on line 949

Warning: min() [function.min]: Array must contain at least one element in \GPXIngest.php on line 950

Warning: Division by zero in \GPXIngest.php on line 952

Warning: Division by zero in \GPXIngest.php on line 953

**Comment by bentasker** [comment] 2016-02-21 20:04
Raised in JIRA as GPXIN-28

Relevant lines are https://github.com/bentasker/PHP-GPX-Ingest/blob/5414ad85e032348864f6c13fbe5867a935f57516/GPXIngest.class.php#L947

**Comment by bentasker** [comment] 2016-02-21 20:05
The cause isn't what I thought it might be - the speeds calculated by `calcDistance` are used to calculate acceleration stats, but it's the lack of those figures which is raising the warning

Could you provide an example of a GPX file which causes these warnings?

I'm going to introduce a check to make sure those arrays aren't empty before operating on them, but it'd be good to check that there isn't another underlying issue in the codebase

**Comment by Qavai** [comment] 2016-02-22 05:24
i think you need do just this


			$this->journey->journeys->$jkey->stats->maxacceleration = !sizeof($this->faccel) ? 0 : max($this->faccel);

**Comment by bentasker** [comment] 2016-02-22 05:48
Yes, pretty much.

What I'm interested in though is what in your GPX file caused it to trigger. Is there a track in there with only one (or maybe 0) trackpoint(s) by any chance?

If you pull the latest, it includes a check to make sure the array's aren't empty before operating on them.

**Comment by Qavai** [comment] 2016-02-22 06:21
[GPS_2010-04-08_070150.gpx.zip](https://github.com/bentasker/PHP-GPX-Ingest/files/140183/GPS_2010-04-08_070150.gpx.zip)

**Comment by bentasker** [comment] 2016-02-22 07:16
Thanks - so the root of the issue is that in that GPX there are no lat/lon changes. If speed hasn't changed (in this case from 0) we don't calculate the rate of acceleration so that array winds up empty, leading to the E_WARNINGs when we try and pass into `max` and `min`

So the non-empty checks should be all that's needed to resolve - though the documentation should probably be updated to note that `stats->avgacceleration` relates to the average rate *whilst accelerating* rather than across the journey as a whole

**Comment by Qavai** [comment] 2016-02-22 17:12
please, fix warnings =)

**Comment by bentasker** [comment] 2016-02-22 19:31
Should already be fixed, was fixed in 4888381

**Closed** 2016-02-23 19:44 UTC
Labels: bug
